export enum Deal {
    ADD_SUCCESS = 'ADD_SUCCESS',
    ADD_FAIL = 'ADD_FAIL',
    ADD_CLEAR = 'ADD_CLEAR',
    GET_LIST_SUCCESS = 'GET_LIST_SUCCESS',
    GET_LIST_FAIL = 'GET_LIST_SUCCESS',
    DELETE_SUCCESS = 'DELETE_SUCCESS',
    DELETE_FAIL = 'DELETE_FAIL',
}
